'use client';

import { format } from 'date-fns';
import {
  FILE_CATEGORY_LABELS, NOTE_CATEGORY_LABELS, PROJECT_STATUS_LABELS,
  type Project, type ProjectFile, type FieldNote, type DeviceEntry,
  type IpPlanEntry, type ActivityLogEntry, type FileCategory,
} from '@/types';
import { formatFileSize } from '@/components/shared/file-icon';
import type { ShareConfig, ShareContentSelection } from './share-types';

interface Props {
  project: Project;
  files: ProjectFile[];
  notes: FieldNote[];
  devices: DeviceEntry[];
  ipEntries: IpPlanEntry[];
  activity: ActivityLogEntry[];
  config: ShareConfig;
}

function maskIp(ip: string): string {
  if (!ip) return ip;
  const parts = ip.split('.');
  return parts.length === 4 ? `${parts[0]}.${parts[1]}.xxx.xxx` : 'xxx.xxx.xxx.xxx';
}

function maskMac(mac: string): string {
  if (!mac) return mac;
  return mac.replace(/[\da-fA-F]{2}/g, (m, i) => i > 5 ? 'XX' : m);
}

function maskPhone(phone: string): string {
  if (!phone) return phone;
  return phone.replace(/\d(?=\d{4})/g, '*');
}

function maskEmail(email: string): string {
  if (!email) return email;
  const [user, domain] = email.split('@');
  return domain ? `${user[0]}***@${domain}` : '***';
}

function filterFiles(files: ProjectFile[], sel: ShareContentSelection): ProjectFile[] {
  if (!sel.sections.files) return [];
  return files.filter(f => sel.fileCategories[f.category as FileCategory]);
}

function fmtDate(iso: string) {
  try { return format(new Date(iso), 'MMM d, yyyy'); } catch { return iso; }
}
function fmtDateTime(iso: string) {
  try { return format(new Date(iso), 'MMM d, yyyy h:mm a'); } catch { return iso; }
}

export function SharePdfView({ project, files, notes, devices, ipEntries, activity, config }: Props) {
  const { content, metadata } = config;
  const mask = content.hideSensitive;
  const detail = content.detailLevel;
  const filteredFiles = filterFiles(files, content);

  return (
    <div className="print-share-view bg-white text-black p-8 max-w-[800px] mx-auto text-sm" style={{ fontFamily: 'system-ui, sans-serif' }}>
      {/* Header */}
      <div className="border-b-2 border-gray-800 pb-4 mb-6">
        <h1 className="text-2xl font-bold text-gray-900">
          {metadata.title || `${project.name} — Project Report`}
        </h1>
        {metadata.coverNote && (
          <p className="mt-2 text-gray-600">{metadata.coverNote}</p>
        )}
        <div className="mt-2 flex gap-4 text-xs text-gray-500">
          {metadata.preparedBy && <span>Prepared by: {metadata.preparedBy}</span>}
          <span>Date: {fmtDate(metadata.date)}</span>
          <span>Generated by BAU Suite</span>
        </div>
      </div>

      {/* Project Info */}
      {content.sections.projectInfo && (
        <section className="mb-6">
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-3">Project Details</h2>
          <div className="grid grid-cols-2 gap-x-8 gap-y-1">
            <InfoItem label="Project" value={project.name} />
            <InfoItem label="Number" value={project.projectNumber} />
            <InfoItem label="Customer" value={project.customerName} />
            <InfoItem label="Status" value={PROJECT_STATUS_LABELS[project.status]} />
            {detail !== 'summary' && (
              <>
                <InfoItem label="Address" value={project.siteAddress} />
                <InfoItem label="Building/Area" value={project.buildingArea} />
              </>
            )}
          </div>
          {detail === 'detailed' && project.tags.length > 0 && (
            <p className="mt-2 text-xs text-gray-500">Tags: {project.tags.join(', ')}</p>
          )}
        </section>
      )}

      {/* Contacts */}
      {content.sections.contacts && project.contacts.length > 0 && (
        <section className="mb-6">
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-3">Contacts</h2>
          <table className="w-full text-xs">
            <thead>
              <tr className="border-b border-gray-200">
                <th className="text-left py-1 font-semibold">Name</th>
                <th className="text-left py-1 font-semibold">Role</th>
                <th className="text-left py-1 font-semibold">Company</th>
                {detail !== 'summary' && (
                  <>
                    <th className="text-left py-1 font-semibold">Phone</th>
                    <th className="text-left py-1 font-semibold">Email</th>
                  </>
                )}
              </tr>
            </thead>
            <tbody>
              {project.contacts.map((c) => (
                <tr key={`${c.name}-${c.role}`} className="border-b border-gray-100">
                  <td className="py-1">{c.name}</td>
                  <td className="py-1">{c.role}</td>
                  <td className="py-1">{c.company || '—'}</td>
                  {detail !== 'summary' && (
                    <>
                      <td className="py-1">{mask && c.phone ? maskPhone(c.phone) : c.phone || '—'}</td>
                      <td className="py-1">{mask && c.email ? maskEmail(c.email) : c.email || '—'}</td>
                    </>
                  )}
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      )}

      {/* Panel Roster */}
      {content.sections.panelRoster && project.panelRosterSummary && (
        <section className="mb-6">
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-3">Panel Roster</h2>
          <p className="whitespace-pre-wrap">{project.panelRosterSummary}</p>
        </section>
      )}

      {/* Technician Notes */}
      {content.sections.techNotes && project.technicianNotes && (
        <section className="mb-6">
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-3">Technician Notes</h2>
          <p className="whitespace-pre-wrap">{project.technicianNotes}</p>
        </section>
      )}

      {/* Network Summary */}
      {content.sections.networkSummary && (ipEntries.length > 0 || project.networkSummary) && (
        <section className="mb-6">
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-3">Network Summary</h2>
          {ipEntries.length > 0 && (
            <div className="flex gap-8 mb-2">
              <span><strong>{ipEntries.length}</strong> IPs</span>
              <span><strong>{[...new Set(ipEntries.map(e => e.subnet).filter(Boolean))].length}</strong> Subnets</span>
              <span><strong>{[...new Set(ipEntries.map(e => e.vlan).filter(Boolean))].length}</strong> VLANs</span>
            </div>
          )}
          {project.networkSummary && <p className="whitespace-pre-wrap">{project.networkSummary}</p>}
        </section>
      )}

      {/* Files */}
      {filteredFiles.length > 0 && (
        <section className="mb-6">
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-3">Files ({filteredFiles.length})</h2>
          {detail === 'summary' ? (
            <ul className="list-disc list-inside">
              {Object.entries(groupBy(filteredFiles, f => f.category)).map(([cat, catFiles]) => (
                <li key={cat}>{FILE_CATEGORY_LABELS[cat as FileCategory]}: {catFiles.length} files</li>
              ))}
            </ul>
          ) : (
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b border-gray-200">
                  <th className="text-left py-1 font-semibold">Title</th>
                  <th className="text-left py-1 font-semibold">Category</th>
                  <th className="text-left py-1 font-semibold">File</th>
                  <th className="text-right py-1 font-semibold">Size</th>
                  <th className="text-left py-1 font-semibold">Rev</th>
                </tr>
              </thead>
              <tbody>
                {filteredFiles.map(f => (
                  <tr key={f.id} className="border-b border-gray-100">
                    <td className="py-1">{f.title}</td>
                    <td className="py-1">{FILE_CATEGORY_LABELS[f.category]}</td>
                    <td className="py-1">{f.fileName}</td>
                    <td className="py-1 text-right">{formatFileSize(f.size)}</td>
                    <td className="py-1">{f.revisionNumber}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </section>
      )}

      {/* Notes */}
      {content.sections.notes && notes.length > 0 && (
        <section className="mb-6">
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-3">Field Notes ({notes.length})</h2>
          {detail === 'summary' ? (
            <ul className="list-disc list-inside">
              {Object.entries(groupBy(notes, n => n.category)).map(([cat, catNotes]) => (
                <li key={cat}>{NOTE_CATEGORY_LABELS[cat as keyof typeof NOTE_CATEGORY_LABELS]}: {catNotes.length}</li>
              ))}
            </ul>
          ) : (
            <div className="space-y-3">
              {notes.map(n => (
                <div key={n.id} className="border border-gray-200 rounded p-2">
                  <div className="flex items-center gap-2 text-xs text-gray-500 mb-1">
                    <span className="font-semibold text-gray-700">[{NOTE_CATEGORY_LABELS[n.category]}]</span>
                    <span>{n.author} — {fmtDateTime(n.createdAt)}</span>
                    {n.isPinned && <span className="text-amber-600">Pinned</span>}
                  </div>
                  <p className="whitespace-pre-wrap">{n.content}</p>
                </div>
              ))}
            </div>
          )}
        </section>
      )}

      {/* Devices */}
      {content.sections.devices && devices.length > 0 && (
        <section className="mb-6">
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-3">Devices ({devices.length})</h2>
          {detail === 'summary' ? (
            <p>{devices.length} devices total</p>
          ) : (
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b border-gray-200">
                  <th className="text-left py-1 font-semibold">Device</th>
                  <th className="text-left py-1 font-semibold">System</th>
                  <th className="text-left py-1 font-semibold">Panel</th>
                  <th className="text-left py-1 font-semibold">Controller</th>
                  <th className="text-left py-1 font-semibold">IP</th>
                  {detail === 'detailed' && <th className="text-left py-1 font-semibold">MAC</th>}
                  <th className="text-left py-1 font-semibold">Status</th>
                </tr>
              </thead>
              <tbody>
                {devices.map(d => (
                  <tr key={d.id} className="border-b border-gray-100">
                    <td className="py-1">{d.deviceName}</td>
                    <td className="py-1">{d.system}</td>
                    <td className="py-1">{d.panel}</td>
                    <td className="py-1">{d.controllerType}</td>
                    <td className="py-1">{mask && d.ipAddress ? maskIp(d.ipAddress) : d.ipAddress || '—'}</td>
                    {detail === 'detailed' && <td className="py-1">{mask && d.macAddress ? maskMac(d.macAddress) : d.macAddress || '—'}</td>}
                    <td className="py-1">{d.status}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </section>
      )}

      {/* IP Plan */}
      {content.sections.ipPlan && ipEntries.length > 0 && (
        <section className="mb-6">
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-3">IP Plan ({ipEntries.length})</h2>
          {detail === 'summary' ? (
            <p>{ipEntries.length} entries total</p>
          ) : (
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b border-gray-200">
                  <th className="text-left py-1 font-semibold">IP</th>
                  <th className="text-left py-1 font-semibold">Hostname</th>
                  <th className="text-left py-1 font-semibold">Panel</th>
                  <th className="text-left py-1 font-semibold">VLAN</th>
                  <th className="text-left py-1 font-semibold">Subnet</th>
                  <th className="text-left py-1 font-semibold">Role</th>
                  <th className="text-left py-1 font-semibold">Status</th>
                </tr>
              </thead>
              <tbody>
                {ipEntries.map(e => (
                  <tr key={e.id} className="border-b border-gray-100">
                    <td className="py-1">{mask ? maskIp(e.ipAddress) : e.ipAddress}</td>
                    <td className="py-1">{e.hostname}</td>
                    <td className="py-1">{e.panel}</td>
                    <td className="py-1">{e.vlan}</td>
                    <td className="py-1">{mask ? maskIp(e.subnet) : e.subnet}</td>
                    <td className="py-1">{e.deviceRole}</td>
                    <td className="py-1">{e.status}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </section>
      )}

      {/* Activity */}
      {content.sections.activity && activity.length > 0 && (
        <section className="mb-6">
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-3">Activity History</h2>
          <ul className="space-y-1 text-xs">
            {(detail === 'summary' ? activity.slice(0, 10) : activity).map(a => (
              <li key={a.id}>
                <span className="text-gray-500">{fmtDateTime(a.timestamp)}</span> — {a.details} <span className="text-gray-400">({a.user})</span>
              </li>
            ))}
          </ul>
        </section>
      )}

      {/* Footer */}
      <div className="border-t border-gray-300 pt-3 mt-8 text-xs text-gray-400 text-center">
        Generated by BAU Suite on {fmtDate(metadata.date)}
      </div>
    </div>
  );
}

function groupBy<T>(arr: T[], key: (item: T) => string): Record<string, T[]> {
  const result: Record<string, T[]> = {};
  for (const item of arr) {
    const k = key(item);
    if (!result[k]) result[k] = [];
    result[k].push(item);
  }
  return result;
}

function InfoItem({ label, value }: { label: string; value: string }) {
  if (!value) return null;
  return (
    <div className="flex gap-2">
      <span className="text-gray-500 font-medium min-w-[90px]">{label}:</span>
      <span>{value}</span>
    </div>
  );
}
