// ─── Report email (.eml) builder ────────────────────────────
// Builds a proper RFC-822 / MIME multipart/mixed message so the user can open
// a complete Outlook/Mail draft with a rich HTML body AND the real attachment
// files embedded. The mailto/clipboard paths cannot carry files — this can.

import { escapeHtml } from '@/lib/utils';
import { getFileBlob } from '@/lib/db';
import type { DailyReport, Project } from '@/types';

export interface ReportEmlMeta {
  title: string;
  preparedBy: string;
  coverNote: string;
}

/** One MIME attachment part, fully prepared (blob already base64-encoded). */
export interface EmlAttachment {
  fileName: string;
  mimeType: string;
  base64: string; // raw base64 (no line wrapping yet)
}

// ─── Subject ────────────────────────────────────────────────
function fmtDateShort(iso: string): string {
  try {
    const d = new Date(iso + (iso.includes('T') ? '' : 'T00:00:00'));
    if (isNaN(d.getTime())) return iso;
    return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  } catch {
    return iso;
  }
}

function fmtDateLong(iso: string): string {
  try {
    const d = new Date(iso + (iso.includes('T') ? '' : 'T00:00:00'));
    if (isNaN(d.getTime())) return iso;
    return d.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
  } catch {
    return iso;
  }
}

/**
 * Default subject for a report export. A user-provided `meta.title` overrides.
 * Always includes the report number when falling back to the default.
 */
export function buildReportSubject(report: DailyReport, project: Project, meta: ReportEmlMeta): string {
  if (meta.title) return meta.title;
  return `Daily Report #${report.reportNumber} – ${project.name} – ${fmtDateShort(report.date)}`;
}

// ─── Plain-text body (mailto / clipboard) ───────────────────
// `attachmentsCarried` controls the honesty of the ATTACHMENTS header:
//   false → text/mailto path (files NOT included) → tells user to attach manually
//   true  → .eml path (files ARE included)         → plain "Attachments:" list
export function buildReportPlainText(
  report: DailyReport,
  project: Project,
  meta: ReportEmlMeta,
  opts: { attachmentsCarried: boolean } = { attachmentsCarried: false },
): string {
  const lines: string[] = [];

  if (meta.coverNote) lines.push(meta.coverNote, '');

  lines.push('REPORT DETAILS');
  lines.push(`Project: ${project.name} (${project.projectNumber})`);
  lines.push(`Date: ${fmtDateLong(report.date)}`);
  lines.push(`Technician: ${report.technicianName || '—'}`);
  if (report.hoursOnSite) lines.push(`Hours On Site: ${report.hoursOnSite}h`);
  if (report.location) lines.push(`Location: ${report.location}`);
  if (report.startTime) lines.push(`Time: ${report.startTime} – ${report.endTime || '?'}`);
  if (report.weather) lines.push(`Weather: ${report.weather}`);
  lines.push('');

  if (report.workCompleted) lines.push('WORK COMPLETED', report.workCompleted, '');
  if (report.issuesEncountered) lines.push('ISSUES ENCOUNTERED', report.issuesEncountered, '');
  if (report.workPlannedNext) lines.push('WORK PLANNED NEXT', report.workPlannedNext, '');
  if (report.equipmentWorkedOn) lines.push('EQUIPMENT WORKED ON', report.equipmentWorkedOn, '');
  if (report.deviceIpChanges) lines.push('DEVICES / IP CHANGES', report.deviceIpChanges, '');
  if (report.coordinationNotes) lines.push('COORDINATION NOTES', report.coordinationNotes, '');
  if (report.safetyNotes) lines.push('SAFETY NOTES', report.safetyNotes, '');
  if (report.generalNotes) lines.push('ADDITIONAL NOTES', report.generalNotes, '');

  if (report.attachments.length > 0) {
    lines.push(opts.attachmentsCarried ? 'ATTACHMENTS' : 'ATTACHMENTS (attach these files manually)');
    for (const a of report.attachments) {
      lines.push(`- ${a.fileName} (${formatSize(a.size)})`);
    }
    lines.push('');
  }

  if (meta.preparedBy) lines.push(`Prepared by ${meta.preparedBy}`);
  lines.push('Generated by BAU Suite');

  return lines.join('\n');
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1048576) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1048576).toFixed(1)} MB`;
}

// ─── HTML body ──────────────────────────────────────────────
// Email-client-safe inline styles. ALL user-entered content is HTML-escaped
// (escapeHtml handles & < > " ') so report text can't break or inject markup.
function nl2br(text: string): string {
  return escapeHtml(text).replace(/\n/g, '<br>');
}

function htmlRow(label: string, value: string): string {
  return `<tr><td style="padding:2px 12px 2px 0;color:#6b7280;font-weight:600;white-space:nowrap;vertical-align:top;">${escapeHtml(label)}</td><td style="padding:2px 0;color:#111827;">${escapeHtml(value)}</td></tr>`;
}

function htmlSection(heading: string, content: string): string {
  return (
    `<div style="margin:0 0 16px 0;">` +
    `<div style="font-weight:700;color:#1f2937;border-bottom:1px solid #d1d5db;padding-bottom:3px;margin-bottom:6px;">${escapeHtml(heading)}</div>` +
    `<div style="color:#374151;line-height:1.5;">${nl2br(content)}</div>` +
    `</div>`
  );
}

export function buildReportHtml(report: DailyReport, project: Project, meta: ReportEmlMeta): string {
  const detailRows: string[] = [];
  detailRows.push(htmlRow('Project', `${project.name} (${project.projectNumber})`));
  detailRows.push(htmlRow('Date', fmtDateLong(report.date)));
  detailRows.push(htmlRow('Technician', report.technicianName || '—'));
  if (report.hoursOnSite) detailRows.push(htmlRow('Hours On Site', `${report.hoursOnSite}h`));
  if (report.location) detailRows.push(htmlRow('Location', report.location));
  if (report.startTime) detailRows.push(htmlRow('Time', `${report.startTime} – ${report.endTime || '?'}`));
  if (report.weather) detailRows.push(htmlRow('Weather', report.weather));

  const sections: string[] = [];
  if (report.workCompleted) sections.push(htmlSection('Work Completed', report.workCompleted));
  if (report.issuesEncountered) sections.push(htmlSection('Issues Encountered', report.issuesEncountered));
  if (report.workPlannedNext) sections.push(htmlSection('Work Planned Next', report.workPlannedNext));
  if (report.equipmentWorkedOn) sections.push(htmlSection('Equipment Worked On', report.equipmentWorkedOn));
  if (report.deviceIpChanges) sections.push(htmlSection('Devices / IP Changes', report.deviceIpChanges));
  if (report.coordinationNotes) sections.push(htmlSection('Coordination Notes', report.coordinationNotes));
  if (report.safetyNotes) sections.push(htmlSection('Safety Notes', report.safetyNotes));
  if (report.generalNotes) sections.push(htmlSection('Additional Notes', report.generalNotes));

  let attachmentsHtml = '';
  if (report.attachments.length > 0) {
    const items = report.attachments
      .map(a => `<li style="margin:2px 0;">${escapeHtml(a.fileName)} <span style="color:#9ca3af;">(${formatSize(a.size)})</span></li>`)
      .join('');
    attachmentsHtml =
      `<div style="margin:0 0 16px 0;">` +
      `<div style="font-weight:700;color:#1f2937;border-bottom:1px solid #d1d5db;padding-bottom:3px;margin-bottom:6px;">Attachments</div>` +
      `<ul style="margin:0;padding-left:20px;color:#374151;">${items}</ul>` +
      `</div>`;
  }

  const coverNoteHtml = meta.coverNote
    ? `<div style="margin:0 0 16px 0;color:#374151;line-height:1.5;">${nl2br(meta.coverNote)}</div>`
    : '';

  const preparedByHtml = meta.preparedBy
    ? `<div style="margin-top:4px;color:#6b7280;font-size:12px;">Prepared by ${escapeHtml(meta.preparedBy)}</div>`
    : '';

  const titleText = meta.title || `Daily Report #${report.reportNumber}`;

  return (
    `<!DOCTYPE html><html><head><meta charset="utf-8"></head>` +
    `<body style="margin:0;padding:0;background:#ffffff;">` +
    `<div style="max-width:720px;margin:0 auto;padding:24px;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;font-size:14px;color:#111827;">` +
    // Header block
    `<div style="border-bottom:2px solid #1f2937;padding-bottom:12px;margin-bottom:20px;">` +
    `<h1 style="margin:0;font-size:20px;color:#111827;">${escapeHtml(titleText)}</h1>` +
    preparedByHtml +
    `</div>` +
    coverNoteHtml +
    // Report details
    `<div style="margin:0 0 16px 0;">` +
    `<div style="font-weight:700;color:#1f2937;border-bottom:1px solid #d1d5db;padding-bottom:3px;margin-bottom:6px;">Report Details</div>` +
    `<table style="border-collapse:collapse;font-size:14px;">${detailRows.join('')}</table>` +
    `</div>` +
    sections.join('') +
    attachmentsHtml +
    // Footer
    `<div style="border-top:1px solid #d1d5db;padding-top:10px;margin-top:24px;color:#9ca3af;font-size:12px;text-align:center;">Generated by BAU Suite</div>` +
    `</div></body></html>`
  );
}

// ─── base64 helpers ─────────────────────────────────────────
/** base64-encode a UTF-8 string (handles non-ASCII via TextEncoder). */
export function utf8ToBase64(str: string): string {
  const bytes = new TextEncoder().encode(str);
  return bytesToBase64(bytes);
}

/** base64-encode raw bytes, chunked to avoid String.fromCharCode call-stack limits. */
export function bytesToBase64(bytes: Uint8Array): string {
  let binary = '';
  const chunk = 0x8000; // 32 KB per chunk
  for (let i = 0; i < bytes.length; i += chunk) {
    const slice = bytes.subarray(i, i + chunk);
    binary += String.fromCharCode(...slice);
  }
  return btoa(binary);
}

/** Wrap a raw base64 string at 76-char lines (RFC 2045). */
export function wrapBase64(b64: string, width = 76): string {
  const out: string[] = [];
  for (let i = 0; i < b64.length; i += width) {
    out.push(b64.slice(i, i + width));
  }
  return out.join('\r\n');
}

// ─── RFC-2047 subject encoding ──────────────────────────────
/** Encode a header value as RFC-2047 base64 if it contains non-ASCII. */
export function encodeHeaderValue(value: string): string {
  const isAscii = [...value].every(ch => ch.charCodeAt(0) < 128);
  if (isAscii) return value;
  return `=?UTF-8?B?${utf8ToBase64(value)}?=`;
}

// ─── .eml assembly (pure) ───────────────────────────────────
/**
 * Assemble a complete multipart/mixed RFC-822 message from a pre-built HTML
 * body and a list of already-base64-encoded attachments. Pure and testable.
 */
export function assembleEml(args: {
  subject: string;
  html: string;
  attachments: EmlAttachment[];
}): string {
  const { subject, html, attachments } = args;
  const boundary = `----=_BAUSuite_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`;
  const CRLF = '\r\n';

  const parts: string[] = [];

  // Top-level headers (draft — no To/From)
  parts.push(
    [
      `Subject: ${encodeHeaderValue(subject)}`,
      `Date: ${new Date().toUTCString()}`,
      `MIME-Version: 1.0`,
      `Content-Type: multipart/mixed; boundary="${boundary}"`,
      '',
      'This is a multi-part message in MIME format.',
      '',
    ].join(CRLF),
  );

  // HTML body part
  parts.push(
    [
      `--${boundary}`,
      `Content-Type: text/html; charset=utf-8`,
      `Content-Transfer-Encoding: base64`,
      '',
      wrapBase64(utf8ToBase64(html)),
      '',
    ].join(CRLF),
  );

  // Attachment parts
  for (const att of attachments) {
    const safeName = att.fileName.replace(/"/g, "'");
    parts.push(
      [
        `--${boundary}`,
        `Content-Type: ${att.mimeType || 'application/octet-stream'}; name="${safeName}"`,
        `Content-Transfer-Encoding: base64`,
        `Content-Disposition: attachment; filename="${safeName}"`,
        '',
        wrapBase64(att.base64),
        '',
      ].join(CRLF),
    );
  }

  // Closing boundary
  parts.push(`--${boundary}--${CRLF}`);

  return parts.join(CRLF);
}

// ─── End-to-end builder (fetches blobs) ─────────────────────
export interface BuildEmlResult {
  eml: string;
  totalAttachmentBytes: number;
  missingAttachments: string[]; // fileNames whose blob was missing
}

/**
 * Build the full .eml string for a report: renders the HTML body, fetches each
 * attachment blob via getFileBlob, base64-encodes it, and assembles the MIME
 * message. Missing blobs are skipped (reported, not fatal).
 */
export async function buildReportEml(
  report: DailyReport,
  project: Project,
  meta: ReportEmlMeta,
): Promise<BuildEmlResult> {
  const subject = buildReportSubject(report, project, meta);
  const html = buildReportHtml(report, project, meta);

  const attachments: EmlAttachment[] = [];
  const missingAttachments: string[] = [];
  let totalAttachmentBytes = 0;

  for (const att of report.attachments) {
    let blob: Blob | undefined;
    try {
      blob = await getFileBlob(att.blobKey);
    } catch {
      blob = undefined;
    }
    if (!blob) {
      missingAttachments.push(att.fileName);
      continue;
    }
    const bytes = new Uint8Array(await blob.arrayBuffer());
    totalAttachmentBytes += bytes.length;
    attachments.push({
      fileName: att.fileName,
      mimeType: att.mimeType || blob.type,
      base64: bytesToBase64(bytes),
    });
  }

  const eml = assembleEml({ subject, html, attachments });
  return { eml, totalAttachmentBytes, missingAttachments };
}
