'use client';

import { useState, useCallback, useRef } from 'react';
import { format } from 'date-fns';
import {
  MessageSquare, Mail, FileDown, Package, ChevronRight, ChevronLeft,
  Copy, Check, Printer, Download,
} from 'lucide-react';
import {
  Dialog, DialogContent, DialogDescription, DialogFooter,
  DialogHeader, DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { cn, escapeHtml } from '@/lib/utils';
import { openUrl } from '@/lib/tauri-bridge';
import { toast } from 'sonner';
import type { DailyReport, Project, ReportAttachment } from '@/types';
import {
  type ShareFormat,
  SHARE_FORMAT_LABELS, SHARE_FORMAT_DESCRIPTIONS,
} from '@/components/share/share-types';

// ─── Props ──────────────────────────────────────────────────
interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  report: DailyReport;
  project: Project;
}

const FORMAT_ICONS: Record<ShareFormat, typeof MessageSquare> = {
  teams: MessageSquare,
  outlook: Mail,
  pdf: FileDown,
  package: Package,
};

const STEPS = ['Format', 'Review & Export'] as const;

// ─── Report Formatters ──────────────────────────────────────
// These reuse the same format patterns from the project share system
// but are tailored for the daily report content structure.

function fmtDate(iso: string) {
  try { return format(new Date(iso + (iso.includes('T') ? '' : 'T00:00:00')), 'MMM d, yyyy'); } catch { return iso; }
}

function fmtLongDate(iso: string) {
  try { return format(new Date(iso + (iso.includes('T') ? '' : 'T00:00:00')), 'EEEE, MMMM d, yyyy'); } catch { return iso; }
}

interface ReportExportMetadata {
  title: string;
  preparedBy: string;
  coverNote: string;
}

function formatReportForTeams(
  report: DailyReport,
  project: Project,
  meta: ReportExportMetadata,
): string {
  const lines: string[] = [];

  lines.push(`## ${meta.title || `Daily Report #${report.reportNumber}`}`);
  if (meta.coverNote) lines.push('', meta.coverNote);
  lines.push('---');

  // Header
  lines.push('', '### Report Details');
  lines.push(`- **Project:** ${project.name} (${project.projectNumber})`);
  lines.push(`- **Date:** ${fmtLongDate(report.date)}`);
  lines.push(`- **Technician:** ${report.technicianName || '—'}`);
  if (report.hoursOnSite) lines.push(`- **Hours On Site:** ${report.hoursOnSite}h`);
  if (report.location) lines.push(`- **Location:** ${report.location}`);
  if (report.startTime) lines.push(`- **Time:** ${report.startTime} – ${report.endTime || '?'}`);
  if (report.weather) lines.push(`- **Weather:** ${report.weather}`);

  // Work Summary
  if (report.workCompleted || report.issuesEncountered || report.workPlannedNext) {
    lines.push('', '### Work Summary');
    if (report.workCompleted) lines.push('', '**Work Completed**', report.workCompleted);
    if (report.issuesEncountered) lines.push('', '**Issues Encountered**', report.issuesEncountered);
    if (report.workPlannedNext) lines.push('', '**Work Planned Next**', report.workPlannedNext);
  }

  // Systems / Equipment
  if (report.equipmentWorkedOn || report.deviceIpChanges) {
    lines.push('', '### Systems / Equipment');
    if (report.equipmentWorkedOn) lines.push('', '**Equipment Worked On**', report.equipmentWorkedOn);
    if (report.deviceIpChanges) lines.push('', '**Devices / IP Changes**', report.deviceIpChanges);
  }

  // Coordination
  if (report.coordinationNotes || report.safetyNotes) {
    lines.push('', '### Coordination');
    if (report.coordinationNotes) lines.push('', '**Coordination Notes**', report.coordinationNotes);
    if (report.safetyNotes) lines.push('', '**Safety Notes**', report.safetyNotes);
  }

  // General Notes
  if (report.generalNotes) {
    lines.push('', '### Additional Notes', report.generalNotes);
  }

  // Attachments
  if (report.attachments.length > 0) {
    lines.push('', '### Attachments');
    for (const a of report.attachments) {
      lines.push(`- ${a.fileName} (${formatSize(a.size)})`);
    }
  }

  if (meta.preparedBy) {
    lines.push('', '---', `*Prepared by ${meta.preparedBy} on ${fmtDate(new Date().toISOString())}*`);
  }
  lines.push('', '---', `*Generated by BAU Suite*`);
  return lines.join('\n');
}

function formatReportForOutlook(
  report: DailyReport,
  project: Project,
  meta: ReportExportMetadata,
): { subject: string; body: string } {
  const subject = meta.title || `Daily Report – ${project.name} – ${fmtDate(report.date)}`;
  const lines: string[] = [];

  if (meta.coverNote) lines.push(meta.coverNote, '');

  lines.push('REPORT DETAILS');
  lines.push(`Project: ${project.name} (${project.projectNumber})`);
  lines.push(`Date: ${fmtLongDate(report.date)}`);
  lines.push(`Technician: ${report.technicianName || '—'}`);
  if (report.hoursOnSite) lines.push(`Hours On Site: ${report.hoursOnSite}h`);
  if (report.location) lines.push(`Location: ${report.location}`);
  if (report.startTime) lines.push(`Time: ${report.startTime} – ${report.endTime || '?'}`);
  if (report.weather) lines.push(`Weather: ${report.weather}`);
  lines.push('');

  if (report.workCompleted) {
    lines.push('WORK COMPLETED', report.workCompleted, '');
  }
  if (report.issuesEncountered) {
    lines.push('ISSUES ENCOUNTERED', report.issuesEncountered, '');
  }
  if (report.workPlannedNext) {
    lines.push('WORK PLANNED NEXT', report.workPlannedNext, '');
  }
  if (report.equipmentWorkedOn) {
    lines.push('EQUIPMENT WORKED ON', report.equipmentWorkedOn, '');
  }
  if (report.deviceIpChanges) {
    lines.push('DEVICES / IP CHANGES', report.deviceIpChanges, '');
  }
  if (report.coordinationNotes) {
    lines.push('COORDINATION NOTES', report.coordinationNotes, '');
  }
  if (report.safetyNotes) {
    lines.push('SAFETY NOTES', report.safetyNotes, '');
  }
  if (report.generalNotes) {
    lines.push('ADDITIONAL NOTES', report.generalNotes, '');
  }
  if (report.attachments.length > 0) {
    lines.push('ATTACHMENTS');
    for (const a of report.attachments) {
      lines.push(`- ${a.fileName} (${formatSize(a.size)})`);
    }
    lines.push('');
  }

  if (meta.preparedBy) lines.push(`Prepared by ${meta.preparedBy}`);
  lines.push('Generated by BAU Suite');

  return { subject, body: lines.join('\n') };
}

function generateReportPackage(
  report: DailyReport,
  project: Project,
  meta: ReportExportMetadata,
): string {
  const pkg = {
    _meta: {
      generator: 'BAU Suite',
      type: 'daily-report',
      exportedAt: new Date().toISOString(),
      preparedBy: meta.preparedBy || undefined,
    },
    report: {
      reportNumber: report.reportNumber,
      date: report.date,
      status: report.status,
      technicianName: report.technicianName,
      startTime: report.startTime || undefined,
      endTime: report.endTime || undefined,
      hoursOnSite: report.hoursOnSite || undefined,
      location: report.location || undefined,
      weather: report.weather || undefined,
      workCompleted: report.workCompleted || undefined,
      issuesEncountered: report.issuesEncountered || undefined,
      workPlannedNext: report.workPlannedNext || undefined,
      equipmentWorkedOn: report.equipmentWorkedOn || undefined,
      deviceIpChanges: report.deviceIpChanges || undefined,
      coordinationNotes: report.coordinationNotes || undefined,
      safetyNotes: report.safetyNotes || undefined,
      generalNotes: report.generalNotes || undefined,
      attachments: report.attachments.map(a => ({
        fileName: a.fileName,
        fileType: a.fileType,
        mimeType: a.mimeType,
        size: a.size,
      })),
      createdAt: report.createdAt,
      updatedAt: report.updatedAt,
    },
    project: {
      name: project.name,
      projectNumber: project.projectNumber,
      customerName: project.customerName,
      siteAddress: project.siteAddress,
    },
  };
  return JSON.stringify(pkg, null, 2);
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1048576) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1048576).toFixed(1)} MB`;
}

// ─── PDF View ───────────────────────────────────────────────
function ReportPdfView({ report, project, meta }: {
  report: DailyReport; project: Project; meta: ReportExportMetadata;
}) {
  return (
    <div className="bg-white text-black p-8 max-w-[800px] mx-auto text-sm" style={{ fontFamily: 'system-ui, sans-serif' }}>
      {/* Header */}
      <div className="border-b-2 border-gray-800 pb-4 mb-6">
        <h1 className="text-2xl font-bold text-gray-900">
          {meta.title || `Daily Report #${report.reportNumber}`}
        </h1>
        {meta.coverNote && <p className="mt-2 text-gray-600">{meta.coverNote}</p>}
        <div className="mt-2 flex gap-4 text-xs text-gray-500">
          {meta.preparedBy && <span>Prepared by: {meta.preparedBy}</span>}
          <span>Date: {fmtLongDate(report.date)}</span>
          <span>Generated by BAU Suite</span>
        </div>
      </div>

      {/* Report Details */}
      <section className="mb-6">
        <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-3">Report Details</h2>
        <div className="grid grid-cols-2 gap-x-8 gap-y-1">
          <PdfInfoItem label="Project" value={`${project.name} (${project.projectNumber})`} />
          <PdfInfoItem label="Customer" value={project.customerName} />
          <PdfInfoItem label="Date" value={fmtLongDate(report.date)} />
          <PdfInfoItem label="Technician" value={report.technicianName} />
          {report.hoursOnSite && <PdfInfoItem label="Hours On Site" value={`${report.hoursOnSite}h`} />}
          {report.location && <PdfInfoItem label="Location" value={report.location} />}
          {report.startTime && <PdfInfoItem label="Time" value={`${report.startTime} – ${report.endTime || '?'}`} />}
          {report.weather && <PdfInfoItem label="Weather" value={report.weather} />}
        </div>
      </section>

      {/* Work Summary */}
      {(report.workCompleted || report.issuesEncountered || report.workPlannedNext) && (
        <section className="mb-6">
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-3">Work Summary</h2>
          {report.workCompleted && (
            <div className="mb-3">
              <p className="font-medium text-gray-700 mb-1">Work Completed</p>
              <p className="whitespace-pre-wrap">{report.workCompleted}</p>
            </div>
          )}
          {report.issuesEncountered && (
            <div className="mb-3">
              <p className="font-medium text-gray-700 mb-1">Issues Encountered</p>
              <p className="whitespace-pre-wrap">{report.issuesEncountered}</p>
            </div>
          )}
          {report.workPlannedNext && (
            <div className="mb-3">
              <p className="font-medium text-gray-700 mb-1">Work Planned Next</p>
              <p className="whitespace-pre-wrap">{report.workPlannedNext}</p>
            </div>
          )}
        </section>
      )}

      {/* Systems / Equipment */}
      {(report.equipmentWorkedOn || report.deviceIpChanges) && (
        <section className="mb-6">
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-3">Systems / Equipment</h2>
          {report.equipmentWorkedOn && (
            <div className="mb-3">
              <p className="font-medium text-gray-700 mb-1">Equipment Worked On</p>
              <p className="whitespace-pre-wrap">{report.equipmentWorkedOn}</p>
            </div>
          )}
          {report.deviceIpChanges && (
            <div className="mb-3">
              <p className="font-medium text-gray-700 mb-1">Devices / IP Changes</p>
              <p className="whitespace-pre-wrap">{report.deviceIpChanges}</p>
            </div>
          )}
        </section>
      )}

      {/* Coordination */}
      {(report.coordinationNotes || report.safetyNotes) && (
        <section className="mb-6">
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-3">Coordination</h2>
          {report.coordinationNotes && (
            <div className="mb-3">
              <p className="font-medium text-gray-700 mb-1">Coordination Notes</p>
              <p className="whitespace-pre-wrap">{report.coordinationNotes}</p>
            </div>
          )}
          {report.safetyNotes && (
            <div className="mb-3">
              <p className="font-medium text-gray-700 mb-1">Safety Notes</p>
              <p className="whitespace-pre-wrap">{report.safetyNotes}</p>
            </div>
          )}
        </section>
      )}

      {/* Additional Notes */}
      {report.generalNotes && (
        <section className="mb-6">
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-3">Additional Notes</h2>
          <p className="whitespace-pre-wrap">{report.generalNotes}</p>
        </section>
      )}

      {/* Attachments */}
      {report.attachments.length > 0 && (
        <section className="mb-6">
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-3">Attachments ({report.attachments.length})</h2>
          <ul className="list-disc list-inside text-xs space-y-1">
            {report.attachments.map(a => (
              <li key={a.id}>{a.fileName} ({formatSize(a.size)})</li>
            ))}
          </ul>
        </section>
      )}

      {/* Footer */}
      <div className="border-t border-gray-300 pt-3 mt-8 text-xs text-gray-400 text-center">
        Generated by BAU Suite on {fmtDate(new Date().toISOString())}
      </div>
    </div>
  );
}

function PdfInfoItem({ label, value }: { label: string; value: string }) {
  if (!value) return null;
  return (
    <div className="flex gap-2">
      <span className="text-gray-500 font-medium min-w-[110px]">{label}:</span>
      <span>{value}</span>
    </div>
  );
}

// ─── Export Dialog ───────────────────────────────────────────
export function ReportExportDialog({ open, onOpenChange, report, project }: Props) {
  const [step, setStep] = useState(0);
  const [selectedFormat, setSelectedFormat] = useState<ShareFormat>('teams');
  const [metadata, setMetadata] = useState<ReportExportMetadata>({
    title: '',
    preparedBy: '',
    coverNote: '',
  });
  const [copied, setCopied] = useState(false);
  const printRef = useRef<HTMLDivElement>(null);

  const reset = useCallback(() => {
    setStep(0);
    setSelectedFormat('teams');
    setMetadata({ title: '', preparedBy: '', coverNote: '' });
    setCopied(false);
  }, []);

  const handleOpenChange = (o: boolean) => {
    if (!o) reset();
    onOpenChange(o);
  };

  // ─── Copy to clipboard ─────────────────────────────────────
  const handleCopy = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      toast.success('Copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error('Failed to copy');
    }
  };

  // ─── Download JSON package ────────────────────────────────
  const handleDownloadPackage = () => {
    const json = generateReportPackage(report, project, metadata);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `report-${report.reportNumber}-${report.date}.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Package downloaded');
  };

  // ─── Print / PDF ──────────────────────────────────────────
  const handlePrint = () => {
    const content = printRef.current;
    if (!content) return;

    // Create a temporary print container in the current window
    const printContainer = document.createElement('div');
    printContainer.id = 'bau-print-container';
    printContainer.innerHTML = content.innerHTML;

    const style = document.createElement('style');
    style.id = 'bau-print-styles';
    style.textContent = `
      @media print {
        body > *:not(#bau-print-container) { display: none !important; }
        #bau-print-container {
          display: block !important;
          position: absolute; top: 0; left: 0; width: 100%;
          font-family: system-ui, -apple-system, sans-serif; font-size: 12px; color: #111; padding: 20px;
        }
        #bau-print-container h1 { font-size: 20px; margin-bottom: 8px; }
        #bau-print-container h2 { font-size: 15px; margin-bottom: 6px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
        #bau-print-container section { margin-bottom: 16px; }
        #bau-print-container table { width: 100%; border-collapse: collapse; }
        #bau-print-container th, #bau-print-container td { text-align: left; padding: 3px 6px; border-bottom: 1px solid #eee; }
        #bau-print-container th { font-weight: 600; background: #f5f5f5; }
        #bau-print-container .text-gray-500 { color: #6b7280; }
        #bau-print-container .text-gray-400 { color: #9ca3af; }
        #bau-print-container .text-gray-600 { color: #4b5563; }
        #bau-print-container .text-gray-700 { color: #374151; }
        #bau-print-container .text-gray-800 { color: #1f2937; }
        #bau-print-container .text-gray-900 { color: #111827; }
        #bau-print-container .font-semibold { font-weight: 600; }
        #bau-print-container .font-medium { font-weight: 500; }
        #bau-print-container .font-bold { font-weight: 700; }
        #bau-print-container .whitespace-pre-wrap { white-space: pre-wrap; }
        #bau-print-container .list-disc { list-style-type: disc; padding-left: 20px; }
        #bau-print-container .border-b-2 { border-bottom: 2px solid #1f2937; }
        #bau-print-container .border-b { border-bottom: 1px solid #d1d5db; }
        #bau-print-container .border-t { border-top: 1px solid #d1d5db; }
      }
      #bau-print-container { display: none; }
    `;
    document.head.appendChild(style);
    document.body.appendChild(printContainer);
    window.print();
    document.body.removeChild(printContainer);
    document.head.removeChild(style);
  };

  // ─── Step 1: Format Selection ─────────────────────────────
  const renderFormatStep = () => (
    <div className="space-y-3 px-5 pb-2">
      <p className="text-sm text-muted-foreground">Choose how you want to export this report.</p>
      <div className="grid gap-2 sm:grid-cols-2">
        {(['teams', 'outlook', 'pdf', 'package'] as ShareFormat[]).map(f => {
          const Icon = FORMAT_ICONS[f];
          return (
            <button
              key={f}
              onClick={() => setSelectedFormat(f)}
              className={cn(
                'flex items-start gap-3 rounded-lg border p-3 text-left transition-all',
                selectedFormat === f
                  ? 'border-primary bg-primary/5 ring-1 ring-primary/30'
                  : 'border-border hover:border-primary/30'
              )}
            >
              <Icon className={cn('h-5 w-5 mt-0.5 shrink-0', selectedFormat === f ? 'text-primary' : 'text-muted-foreground')} />
              <div>
                <p className="text-sm font-medium">{SHARE_FORMAT_LABELS[f]}</p>
                <p className="text-xs text-muted-foreground">{SHARE_FORMAT_DESCRIPTIONS[f]}</p>
              </div>
            </button>
          );
        })}
      </div>
    </div>
  );

  // ─── Step 2: Review & Export ───────────────────────────────
  const renderReviewStep = () => {
    const teamsOutput = selectedFormat === 'teams' ? formatReportForTeams(report, project, metadata) : '';
    const outlookOutput = selectedFormat === 'outlook' ? formatReportForOutlook(report, project, metadata) : null;

    return (
      <div className="space-y-4 px-5 pb-2">
        {/* Metadata fields */}
        <div className="grid gap-3 sm:grid-cols-2">
          <div className="space-y-1.5 sm:col-span-2">
            <Label htmlFor="report-export-title">Title (optional)</Label>
            <Input
              id="report-export-title"
              placeholder={`Daily Report #${report.reportNumber} – ${project.name}`}
              value={metadata.title}
              onChange={e => setMetadata(m => ({ ...m, title: e.target.value }))}
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="report-export-by">Prepared By</Label>
            <Input
              id="report-export-by"
              placeholder="Your name"
              value={metadata.preparedBy}
              onChange={e => setMetadata(m => ({ ...m, preparedBy: e.target.value }))}
            />
          </div>
          <div className="space-y-1.5 sm:col-span-2">
            <Label htmlFor="report-export-note">Cover Note</Label>
            <Textarea
              id="report-export-note"
              placeholder="Optional message to include at the top..."
              value={metadata.coverNote}
              onChange={e => setMetadata(m => ({ ...m, coverNote: e.target.value }))}
              rows={2}
              className="resize-none"
            />
          </div>
        </div>

        {/* Preview */}
        <div>
          <Label className="text-xs uppercase tracking-wider text-muted-foreground mb-2 block">Preview</Label>
          {selectedFormat === 'teams' && (
            <div className="rounded-lg border border-border bg-muted/30 p-3" style={{ maxHeight: '30vh', overflowY: 'auto' }}>
              <pre className="text-xs whitespace-pre-wrap font-mono">{teamsOutput}</pre>
            </div>
          )}
          {selectedFormat === 'outlook' && outlookOutput && (
            <div className="space-y-2">
              <div className="rounded-lg border border-border bg-muted/30 p-3">
                <p className="text-xs font-medium text-muted-foreground mb-1">Subject:</p>
                <p className="text-sm font-medium">{outlookOutput.subject}</p>
              </div>
              <div className="rounded-lg border border-border bg-muted/30 p-3" style={{ maxHeight: '25vh', overflowY: 'auto' }}>
                <p className="text-xs font-medium text-muted-foreground mb-1">Body:</p>
                <pre className="text-xs whitespace-pre-wrap font-mono">{outlookOutput.body}</pre>
              </div>
            </div>
          )}
          {selectedFormat === 'pdf' && (
            <div className="rounded-lg border border-border bg-white" style={{ maxHeight: '30vh', overflowY: 'auto' }}>
              <div ref={printRef} style={{ transform: 'scale(0.7)', transformOrigin: 'top left', width: '142%' }}>
                <ReportPdfView report={report} project={project} meta={metadata} />
              </div>
            </div>
          )}
          {selectedFormat === 'package' && (
            <div className="rounded-lg border border-border bg-muted/30 p-3" style={{ maxHeight: '30vh', overflowY: 'auto' }}>
              <pre className="text-xs whitespace-pre-wrap font-mono">
                {generateReportPackage(report, project, metadata).substring(0, 2000)}
                {generateReportPackage(report, project, metadata).length > 2000 ? '\n...' : ''}
              </pre>
            </div>
          )}
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-2">
          {selectedFormat === 'teams' && (
            <Button onClick={() => handleCopy(teamsOutput)} className="gap-1.5">
              {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
              {copied ? 'Copied!' : 'Copy to Clipboard'}
            </Button>
          )}
          {selectedFormat === 'outlook' && outlookOutput && (
            <>
              <Button onClick={() => handleCopy(`Subject: ${outlookOutput.subject}\n\n${outlookOutput.body}`)} className="gap-1.5">
                {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                {copied ? 'Copied!' : 'Copy Email'}
              </Button>
              <Button
                variant="outline"
                onClick={() => {
                  const mailto = `mailto:?subject=${encodeURIComponent(outlookOutput.subject)}&body=${encodeURIComponent(outlookOutput.body)}`;
                  openUrl(mailto);
                }}
                className="gap-1.5"
              >
                <Mail className="h-4 w-4" /> Open in Email
              </Button>
            </>
          )}
          {selectedFormat === 'pdf' && (
            <Button onClick={handlePrint} className="gap-1.5">
              <Printer className="h-4 w-4" /> Print / Save as PDF
            </Button>
          )}
          {selectedFormat === 'package' && (
            <Button onClick={handleDownloadPackage} className="gap-1.5">
              <Download className="h-4 w-4" /> Download Package
            </Button>
          )}
        </div>
      </div>
    );
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="max-w-lg">
        <div style={{ maxHeight: '85vh', overflowY: 'auto' }}>
          <DialogHeader>
            <DialogTitle>Export / Share Report</DialogTitle>
            <DialogDescription>
              Export Daily Report #{report.reportNumber} for {fmtLongDate(report.date)}
            </DialogDescription>
          </DialogHeader>

          {/* Step Indicator */}
          <div className="flex items-center gap-2 px-5 py-3">
            {STEPS.map((label, i) => (
              <div key={label} className="flex items-center gap-2 flex-1">
                <button
                  onClick={() => i < step && setStep(i)}
                  className={cn(
                    'flex items-center gap-1.5 text-xs font-medium transition-colors',
                    i === step ? 'text-primary' : i < step ? 'text-foreground cursor-pointer hover:text-primary' : 'text-muted-foreground'
                  )}
                  disabled={i > step}
                >
                  <span className={cn(
                    'flex h-5 w-5 items-center justify-center rounded-full text-[10px] font-bold',
                    i === step ? 'bg-primary text-primary-foreground' : i < step ? 'bg-primary/20 text-primary' : 'bg-muted text-muted-foreground'
                  )}>
                    {i < step ? <Check className="h-3 w-3" /> : i + 1}
                  </span>
                  <span className="hidden sm:inline">{label}</span>
                </button>
                {i < STEPS.length - 1 && (
                  <div className={cn('h-px flex-1', i < step ? 'bg-primary/30' : 'bg-border')} />
                )}
              </div>
            ))}
          </div>

          {/* Step Content */}
          {step === 0 && renderFormatStep()}
          {step === 1 && renderReviewStep()}

          <DialogFooter>
            {step > 0 && (
              <Button variant="outline" onClick={() => setStep(s => s - 1)} className="gap-1">
                <ChevronLeft className="h-4 w-4" /> Back
              </Button>
            )}
            <div className="flex-1" />
            {step === 0 && (
              <Button variant="outline" onClick={() => handleOpenChange(false)}>Cancel</Button>
            )}
            {step < 1 && (
              <Button onClick={() => setStep(s => s + 1)} className="gap-1">
                Next <ChevronRight className="h-4 w-4" />
              </Button>
            )}
            {step === 1 && (
              <Button variant="outline" onClick={() => handleOpenChange(false)}>Done</Button>
            )}
          </DialogFooter>
        </div>
      </DialogContent>
    </Dialog>
  );
}
